### ISSUE TITLE
[TODO] 6/28 수업 MySQL 

### ISSUE THREAD

**Issue by JungHyeonmin** [JungHyeonmin/MTVS-3rd-Backend-DailyLog#1]
# 데이터 모델링

##🍀작업 사항 check

- [ ] 데이터베이스 설계
- [ ] 데이터모델링의 시작
- [ ] DB모델링의 주요 개념
- [ ] ERD 표기법
- [ ] 데이터 모델링 절차
- [ ] 데이터 베이스 요구사항 분석
- [ ] 엔티티 정의
- [ ] 범주화와 추상화
- [ ] 주 식별자 정의

##⏰예상 기간
6월28일 9:30 ~ 18:30
