### ISSUE TITLE
[TODO] 6/29 (토)~ 6/30 (일) 1주차 Spring Core 복습 및 예제 풀기, CS스터디

### ISSUE THREAD

**Issue by JungHyeonmin** [JungHyeonmin/MTVS-3rd-Backend-DailyLog#2]
# 1주차 Spring Core 복습 및 예제 풀기, CS스터디 - 자바 메모리 구조

##🍀작업 사항 check
- [x] SpringFramework 개요 및 개발환경 구측
- [x] IoC Container
- [x] Dependency Injection
- [x] DI Annotation
- [x] Bean - init, destroy-method xml 부터 시작
- [ ] AOP

- [x] CS스터디 - 자바 메모리 구조 공부,  ppt 만들기

##⏰예상 기간
6월29일 ~ 6월30일
